import type { Metadata } from 'next';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import './globals.css';
import { inter, fontVazir } from '../lib/Fonts';
import CssBaseline from '@mui/material/CssBaseline';
import { ThemeProvider } from '@mui/material/styles';
import theme from '@/lib/Theme';
import EmotionRegistry from '@/lib/EmotionRegistery';
import { NextIntlClientProvider } from 'next-intl';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.variable} ${fontVazir.variable}`}>
        <EmotionRegistry>
          <AppRouterCacheProvider options={{ enableCssLayer: true }}>
            <ThemeProvider theme={theme}>
              <CssBaseline />
              <NextIntlClientProvider>{children}</NextIntlClientProvider>
            </ThemeProvider>
          </AppRouterCacheProvider>
        </EmotionRegistry>
      </body>
    </html>
  );
}
